// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDiLgcHhFdAjpo4wFV_0LLMMbIMiQu3I',
    appId: '1:268859092110:web:3e2fa103f685c9e680addf',
    messagingSenderId: '268859092110',
    projectId: 'campusshelf-b3733',
    authDomain: 'campusshelf-b3733.firebaseapp.com',
    storageBucket: 'campusshelf-b3733.firebasestorage.app',
    measurementId: 'G-5R1BVZFJGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoDiLgcHhFdAjpo4wFV_0LLMMbIMiQu3I',
    appId: '1:268859092110:android:3e2fa103f685c9e680addf',
    messagingSenderId: '268859092110',
    projectId: 'campusshelf-b3733',
    storageBucket: 'campusshelf-b3733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoDiLgcHhFdAjpo4wFV_0LLMMbIMiQu3I',
    appId: '1:268859092110:ios:3e2fa103f685c9e680addf',
    messagingSenderId: '268859092110',
    projectId: 'campusshelf-b3733',
    storageBucket: 'campusshelf-b3733.firebasestorage.app',
    iosBundleId: 'com.example.campus_shelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoDiLgcHhFdAjpo4wFV_0LLMMbIMiQu3I',
    appId: '1:268859092110:macos:3e2fa103f685c9e680addf',
    messagingSenderId: '268859092110',
    projectId: 'campusshelf-b3733',
    storageBucket: 'campusshelf-b3733.firebasestorage.app',
    iosBundleId: 'com.example.campus_shelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoDiLgcHhFdAjpo4wFV_0LLMMbIMiQu3I',
    appId: '1:268859092110:windows:3e2fa103f685c9e680addf',
    messagingSenderId: '268859092110',
    projectId: 'campusshelf-b3733',
    authDomain: 'campusshelf-b3733.firebaseapp.com',
    storageBucket: 'campusshelf-b3733.firebasestorage.app',
  );
}
